/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package team.emergence._15puzzle;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import team.emergence._15puzzle.controller.LauncherController;
import team.emergence._15puzzle.controller.ResultController;
import team.emergence._15puzzle.util.ResourceLoader;

import java.util.Objects;

public class App extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        primaryStage.setTitle("15 Game");
        FXMLLoader loader = new FXMLLoader(ResourceLoader.loadResourceURL("team/emergence/_15puzzle/fxml/Launcher.fxml"));
        Parent root = loader.load();

        LauncherController controller = loader.getController();
        controller.setParameters(getParameters());

        Scene scene = new Scene(root);
        scene.getStylesheets().add(Objects.requireNonNull(getClass().getResource("app.css")).toExternalForm());
        primaryStage.setScene(scene);
        primaryStage.show();
    }
}
