/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("org.openjfx.javafxplugin") version "0.0.10"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()

    jcenter()
    maven("https://nexus.gluonhq.com/nexus/content/repositories/releases/")
}

dependencies {
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13.2")
    
    implementation("com.gluonhq:charm:2.0.0")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")
}

application {
    // Define the main class for the application.
    mainClass.set("team.emergence._15puzzle.App")
}

javafx {
    modules("javafx.controls", "javafx.fxml", "javafx.swing")
}
